export interface regIdPaciente{
    numExped: string,
    nomPaciente: string,
    numEpisodio: string,
    habitacion: string,
    fechaNac: string, 
    edadPaciente: string,
    genero: string,
    fechaIn: string,
    diagnostico: string,
    tipoCx: string,
    cie10: string,
    valorCie10: string,
    lblCie10: string,
    cie9: string,
    valorCie9: string,
    lblCie9: string,
    cirugia: string,
    fechaCx: string,
    hrCx: string,
    cirujano: string,
    anestesiologo: string,
    anestesiologoVPA: string,
    residenteAnestsia: string

    nacionalidad: string,
    valorNac: string,
    lblNac: string,    
    CURP: string,
    folioID: string,
    estNacimiento: string, 
    valorEst: string,
    lblEst: string   
    estResidencia: string,
    valorEstRes: string,
    lblEstRes: string
    alcaldia: string,
    colonia: string,
    codigoPostal
}