export interface regIdPaciente{
    numExped: string,
    nomPaciente: string,
    numEpisodio: string,
    habitacion: string,
    fechaNac: string, 
    edadPaciente: string,
    genero: string,
    fechaIn: string,
    diagnostico: string,
    tipoCx: string,
    cie10: string,
    cie9: string,
    cirugia: string,
    fechaCx: string,
    hrCx: string,
    cirujano: string,
    anestesiologo: string,
    anestesiologoVPA: string,
}