/* Modelado para obtener los datos desde las vistas del registro Transanestésico */
/* Datos del Ventilador */
export interface regMenuTrans{
    // DatosVentilador
    idVentilador: string,
    modosVentilacion: string,
    peep: string,
    vt: string,
    frecResp: string,
    IE: string,
    PLimite: string,
    Hr: string,
    /* Balance Total */
    balanceTotal:number,
    // Ingresos
    solHartman: number,
    solFisio: number,
    glucosados: number,
    gelatinas: number,
    almidones: number,
    albuminas: number,
    paqGlobular: number,
    plasmas: number,
    plaquetas: number,
    crioprecipitados: number,
    factor_VII: number,
    factor_VIII: number,
    otrosIngresos: number,
    // Egresos
    liqAscitis: number,
    sangradoAprox: number,
    uresis: number,
    expoQX: number,
    reqBasales: number,
    ayuno: number,
    otrosEgresos: number,
    /* Técnica Anestésica */
    local: string,
    sedación: string,
    gralBalanceada: string,
    TIVA: string,
    multimodal: string,
    bloqMixto: string,
    bloqPeriLum: string,
    bloqPeriCaudal: string,
    BloqEspinal: string,
    BloqPlexo: string,
    BloqTroncular: string,
    bloqPeriToracico: string,
    bloqPeriCervical: string,
    libreOpioides: string,
}